name: github-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout ğŸ›ï¸
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: Setup Haxe ğŸ•¹ï¸
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install dependencies ğŸ²
        run: yes | haxelib --quiet install build-js.hxml
      # Could add a actions/cache@v1 to speedup packages?

      - name: Build asset package ğŸ®
        run: bash run buildres_py

      - name: Compile ğŸ› ï¸
        run: bash run compile

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: www